### ISSUE TITLE
Do not define "NULL" string as a default value at nextflow_schema.json

### ISSUE THREAD

**Issue by jordeu** [nf-core/scflow#9]
## Description
Some fields at `nextflow_schema.json` file define default values like an string (`"default": "NULL"`) this will be a problem in the upcoming version of [tower.nf](https://tower.nf/). The "NULL" string will be set at the launchpad form and send to Nextflow when launching the pipeline. Finally the run will fail because Nextflow will interpret it as a string and not as an empty parameter.

## Solution
Aligned with the discussion [here](https://github.com/nf-core/tools/issues/992) about enforcing stricter rules for initialising params with no default value, I suggest to just set this fields to `null` at `nextflow.config` file and remove the default setting from the schema file. This will be compatible with the future [tower.nf](https://tower.nf/) release.

**Comment by combiz** [comment]
Most parameters in this pipeline are passed at the command line to R, where the string "NULL" is subsequently parsed inside R to the R `NULL`.  e.g.
`scflow_dirichlet.r     --unique_id_var individual     --celltype_var cluster_celltype     --dependent_var diagnosis     --ref_class Control     --var_order NULL     --sce_path final_sce`.
So the 'NULL' string is a user-specified string parameter for CL tools rather than a groovy `null` value used by NF code.  Will this cause issues?

**Comment by jordeu** [comment]
Ok, then this should work as it is at `tower.nf`, given that the `NULL` parameter will be forwarded as an string to Nextflow. 

Even though I'll define them as groovy `null` values and then convert them to R `NULL` string at task definition, something like these should work:
```
script:
      """
      scflow_dirichlet.r \
      --sce_path ${sce} \
      --unique_id_var ${params.dirich_unique_id_var} \
      --celltype_var ${params.dirich_celltype_var} \
      --dependent_var ${params.dirich_dependent_var} \
      --ref_class ${params.dirich_ref_class} \
      --var_order ${params.dirich_var_order ?: 'NULL'} 
      """
```

But this is just my preference, so feel free to close this issue as it is. Thanks for checking it!

**Comment by combiz** [comment]
Thanks, I think the conversion at task definition is a good idea and would make the params and schema more coherent.  Will make those changes.

**Comment by combiz** [comment]
Can we perhaps generalize this solution to encompass `null`, `true` and `false` also?

```
​def paramParse( inParam ) {
    if (inParam == null) {
        outParam = 'NULL'
    } else if (inParam == true) {
        outParam = 'TRUE'
    } else if (inParam == false) {
        outParam = 'FALSE'
    } else {
      outParam = inParam
    }
return(outParam)
}
```

Then wrap every parameter?

```
script:
      """
      scflow_dirichlet.r \
      --sce_path ${sce} \
      --unique_id_var ${paramParse(params.dirich_unique_id_var)} \
      --celltype_var ${paramParse(params.dirich_celltype_var)} \
      --dependent_var ${paramParse(params.dirich_dependent_var)} \
      --ref_class ${paramParse(params.dirich_ref_class)} \
      --var_order ${paramParse(params.dirich_var_order)} 
      """
```
